# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 554db9580617a0c0fcba245fff1bedbd2ee0b8aab65e5e35d1408009b5a81daac5e8358e0cc1987ead5e8c6eed74139175ad2cc3be3a64430f34215a8cc8a851

test:
  secret_key_base: 390e8d883fb44a862f6a7a2e412de56159856210c5a97fcdf4e00085c49d0d1782ef251ad11b393cfb3e5d47905aa607fd811a7b343f84713adc2624b38115ef

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
